// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ayigojaycbrfovjikuse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aWdvamF5Y2JyZm92amlrdXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzY4MDUsImV4cCI6MjA2OTYxMjgwNX0.lLsxYQ-lXEnSz8aW8dJrSkLW-uHooge-3OeULJZL3tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);